#-------------------
# Module 30 
#-------------------

name: My-GitHubActions

on: [pull_request, push]

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Inspect files
      uses: actions/checkout@v3
      
    - name: Install dependencies   
      run: pip install -r requirements.txt
        
    - name: Run test    
      run: pytest test_main.py
        
    
  my_lintering:
    runs-on: ubuntu-latest
    needs: [my_testing]

    steps:
      - name: Install linters
        run: pip install black isort

      - name: Inspect files
        uses: actions/checkout@v3

      - name: Lintering code
        run: isort --profile black *.py
