#-------------------
# Module 30 
#-------------------

name: My-GitHubActions

on: [pull_request, push]

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Inspect files
      uses: actions/checkout@v1
      
    - name: Install dependencies   
      run: pip install -r requirements.txt
        
    - name: Run test    
      run: pytest test_main.py
