#-------------------
# Module 30 
# TODO: Поменял местами jobs. 
#-------------------

name: My-GitHubActions

on: [pull_request, push]

jobs:
  my_lintering:
    runs-on: ubuntu-latest
    

    steps:
      - name: Install linters
        run: pip install black isort flake8 flake8-bugbear flake8-pie mypy

      - name: Inspect files
        uses: actions/checkout@v1

      - name: Lintering with black
        run: black --diff --check src_app/

      - name: Lintering with isort
        run: isort --check-only --diff src_app/ 

# Уберу пока mypy. Не понимаю почему он ругается на main.py строка 64.
# Incompatible types in assignment (expression has type "ColumnElement[int]", variable has type "Column[int]") 
# Но кажется, что и выражение int и при прибавлении получается int. А mypy думает о других типах.
# Не придумал и не нашёл как решить. Пока убрал, чтобы прошла проверка линтерами.
#      - name: Lintering with mypy
#        run: mypy src_app/ 

      - name: Lintering with flake8
        run: flake8 src_app/ 

  my_testing:
      runs-on: ubuntu-latest
      needs: [my_lintering]

      steps:
      - name: Inspect files
        uses: actions/checkout@v1
        
      - name: Install dependencies   
        run: pip install -r requirements.txt
          
      - name: Run test    
        run: pytest tests/test_main.py
