#-------------------
# Module 30 
#-------------------

name: My-GitHubActions

on: [pull_request, push]

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Inspect files
      uses: actions/checkout@v1
      
    - name: Install dependencies   
      run: pip install -r requirements.txt
        
    - name: Run test    
      run: pytest tests/test_main.py
        
    
  my_lintering:
    runs-on: ubuntu-latest
    needs: [my_testing]

    steps:
      - name: Install linters
        run: pip install black isort flake8 flake8-bugbear flake8-pie mypy

      - name: Inspect files
        uses: actions/checkout@v1

      - name: Lintering with black
        continue-on-error: true
        run: black --diff --check src_app/

      - name: Lintering with isort
        continue-on-error: true
        run: isort --check-only --diff src_app/ 

      - name: Lintering with mypy
        continue-on-error: true
        run: mypy src_app/ 

      - name: Lintering with flake8
        continue-on-error: true
        run: flake8 src_app/ 
