#-------------------
# Module 30 
# TODO: Не знаю насколько правильно, что тестирование перед проверкой линтерами.
# Я делал с такой логикой, что если код не тестируется, то его нет смысла и проверять дальше.
# Поэтому если тесты не прошли, то линтеры не запустятся.
# У линтеров я мог бы на самом деле сделать проверку каждым как отдельная job. Но может есть смысл и в том,
# что если проверка black не прошла, то другими тоже уже нет смысла смотреть.
#-------------------

name: My-GitHubActions

on: [pull_request, push]

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Inspect files
      uses: actions/checkout@v1
      
    - name: Install dependencies   
      run: pip install -r requirements.txt
        
    - name: Run test    
      run: pytest tests/test_main.py
        
    
  my_lintering:
    runs-on: ubuntu-latest
    needs: [my_testing]

    steps:
      - name: Install linters
        run: pip install black isort flake8 flake8-bugbear flake8-pie mypy

      - name: Inspect files
        uses: actions/checkout@v1

      - name: Lintering with black
        run: black --diff --check src_app/

      - name: Lintering with isort
        run: isort --check-only --diff src_app/ 

      - name: Lintering with mypy
        run: mypy src_app/ 

      - name: Lintering with flake8
        run: flake8 src_app/ 
